#!/usr/bin/perl
use strict;
use warnings;

use lib 'lib';
use lib 't/lib';

use Dist::Zilla;

use Path::Class;

use File::Temp qw(tempdir);
use Moose::Autobox;

my $root   = $ARGV[0] || '.';
my $target = $ARGV[1] || tempdir(DIR => '.');

my $dist = Dist::Zilla->from_dir( dir($root) );

$dist->build_dist($target);
